version: "3.9"
services:
  service-registry:
    build: ./Backend/Service-Registry
    container_name: service-registry
    ports:
      - "8761:8080"

  config-server:
    build: ./Backend/config-Server
    container_name: config-server
    ports:
      - "8888:8080"
    depends_on:
      - service-registry

  api-gateway:
    build: ./Backend/API-Gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
      - config-server

  authorization-service:
    build: ./Backend/Authorization-Service
    container_name: authorization-service
    depends_on:
      - service-registry
      - config-server

  cart-service:
    build: ./Backend/Cart-Service
    container_name: cart-service
    depends_on:
      - service-registry
      - config-server

  catalog-service:
    build: ./Backend/Catalog-Service
    container_name: catalog-service
    depends_on:
      - service-registry
      - config-server

  customer-service:
    build: ./Backend/Customer-Service
    container_name: customer-service
    depends_on:
      - service-registry
      - config-server

  delivery-service:
    build: ./Backend/Delivery-Service
    container_name: delivery-service
    depends_on:
      - service-registry
      - config-server

  order-service:
    build: ./Backend/Order-Service
    container_name: order-service
    depends_on:
      - service-registry
      - config-server

  payment-service:
    build: ./Backend/Payment-Service
    container_name: payment-service
    depends_on:
      - service-registry
      - config-server

  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
