services:
  service-registry:
    build: ./Backend/Service-Registry
    container_name: service-registry
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 10

  config-server:
    build: ./Backend/config-Server
    container_name: config-server
    ports:
      - "8888:8888"
    volumes:
      - ./config-repo:/app/config-repo
    depends_on:
      - service-registry

  api-gateway:
    build: ./Backend/API-Gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_started

  authorization-service:
    build: ./Backend/Authorization-Service
    container_name: authorization-service
    ports:
      - "8081:8080"
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_started

  cart-service:
    build: ./Backend/Cart-Service
    container_name: cart-service
    ports:
      - "8082:8080"
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_started
  catalog-service:
    build: ./Backend/Catalog-Service
    container_name: catalog-service
    ports:
      - "8083:8080"
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_started

  customer-service:
    build: ./Backend/Customer-Service
    container_name: customer-service
    ports:
      - "8085:8080"
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_started

  delivery-service:
    build: ./Backend/Delivery-Service
    container_name: delivery-service
    ports:
      - "8086:8080"
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_started

  order-service:
    build: ./Backend/Order-Service
    container_name: order-service
    ports:
      - "8087:8080"
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_started

  payment-service:
    build: ./Backend/Payment-Service
    container_name: payment-service
    ports:
      - "8088:8080"
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_started
  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway

  cassandra:
    image: bitnami/cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=FoodAppCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_START_RPC=true

