server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/deliveries/**
        - id: service-registry
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
        - id: config-service
          uri: lb://config-service
          predicates:
            - Path=/config/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/carts/**
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalogs/**
        - id: authorization-service
          uri: lb://authorization-service
          predicates:
            - Path=/auth/**
    loadbalancer:
      ribbon:
        enabled: true
